apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  POSTGRES_USER: cm9vdA==  # Base64 encoded 'root'
  POSTGRES_PASSWORD: cm9vdHBhc3N3b3Jk  # Base64 encoded 'rootpassword'
  POSTGRES_DB: bXlkYg==  # Base64 encoded 'mydb'
